### ISSUE TITLE
Related toolkits

### ISSUE THREAD

**Issue by innovativeangela** [oecd-opsi/meta-toolkit#13]
On each toolkit detail page, other toolkits are dynamically displayed if they match the field "Discipline or Practice." These are currently sorted in order of most recently added. 

These should be sorted/displayed instead based on relevance, including:
Same Discipline or Practice
Number of other users who have clicked "I have used this toolkit"  
Number of times it has been saved 
Number of times it has been viewed 
Number of times other users have viewed a given toolkit as well as the toolkit currently being viewed on the detail page
Number of times other users have clicked "I have used this toolkit" as well as the toolkit currently being viewed on the detail page

This feature depends on others (Save + "I have used this toolkit") and requires web storage of user data.

The description of this section should be changed from "Other toolkits related to [Discipline or Practice]" to "Related toolkits"

**Comment by marcochiesi** [comment]
An idea for this implementation could be to have a "relevance" score for each toolkit, which is obtained with a weighted formula that depends on (some of) the parameters you mentioned:
- Number of other users who have clicked "I have used this toolkit"
- Number of times it has been saved
- Number of times it has been viewed

In a first release, I would not use the following criteria because they add a lot of complexity for the computation of the score:
- Number of times other users have viewed a given toolkit as well as the toolkit currently being viewed on the detail page
- Number of times other users have clicked "I have used this toolkit" as well as the toolkit currently being viewed on the detail page

That's because these criteria require to analyze all the toolkits used/viewed by all the users, while the previous ones are basically simple counters.

Once the score is calculated, it can be stored in a custom field of the Toolkit, and it can be used for sorting purposes in an easy way (this is good because it would be hard to apply complex sort criteria at SQL or WP Query level).

Please let me know your thoughts about this.

**Comment by innovativeangela** [comment]
I agree with your alternate relevance scoring method (with the three parameters you mentioned) for the first release. I am still interested in including the other parameters for future releases if WP allows it.

**Comment by innovativeangela** [comment]
Since these would be based on simple counters in your alternate proposal, I suggest changing the label from "Relevance" to "Popularity"

**Comment by marcochiesi** [comment]
Added this feature request to the milestone (at the moment it includes only the 3 aforementioned parameters, the other ones may be added in future releases).

**Comment by fabio-bs** [comment]
I implemented the visit counting system and the two buttons "I have used this toolkit" and "Save toolkit" positioning them under the toolkit title. After expressing their choice, users can also remove it by clicking on the respective links.
The system calculates the popularity of each toolkit once a day using the following formula: 30*(#I have used this toolkit) + 20*(#times it has been saved) + #times it has been viewed.
As a result, the other toolkits listed on the page are shown for relevance to the same discipline or practice and sorted by descending popularity.
