### ISSUE TITLE
Sort

### ISSUE THREAD

**Issue by innovativeangela** [oecd-opsi/meta-toolkit#3]
Sort functionality on the toolkit filter page https://oecd-opsi.org/search-toolkits/
Sort by relevance (depends on data from: most reviewed, "Save" and "I have used this" features), year published, date added.

**Comment by marcochiesi** [comment]
Please see #13 as it's strictly related to this one.
The idea is to use a custom field to take into consideration the relevance.
By the way at the moment the "Search & Filter" plugin only allows for two sort criteria, so I would stick with i.e. relevance + year, or relevance + date added.

**Comment by innovativeangela** [comment]
Ok. Let's go with Relevance (except substitute with the label "Popularity" since your proposed alternative is based on simple counters). 
I am still not sure about the second sort criteria. 
I assume that Date Added will reference the date of entry to WP. In this case, most of the toolkits will have the same date since they were uploaded in bulk. This sort option would only become useful as new toolkits are added via the toolkit submission form. Is that correct?
For the Year-based sort, we need to figure out how to prioritise toolkits that do not have a year (such as web-based toolkits). Do you have a suggestion?

**Comment by marcochiesi** [comment]
I don't think the second criteria will be so important as it will be used only when the first one (Popularity) has the same value. Since the Popularity score is built upon 3 different values I believe it's unlikely that there will be Toolkits having the exact same score, if we use a proper calculation of the score.
Anyway, since not all the Toolkits have a year, probably it's better to leverage the Date Added field. That way new Toolkits will have priority but you will still be able to adjust the dates of existing Toolkits to force the order you want.
Alternatively, we could use an explicit "position" field so that you can force the order in a completely manual way. This is the way that WordPress uses to force the position of the pages for example. Anyway, I wouldn't recommend this last option as it would require a manual adjustment each time a new Toolkit is added.

**Comment by fabio-bs** [comment]
I made the change on the staging site, now the search results are sorted by descending toolkit popularity.
